### ISSUE TITLE
whatwaf --help not working

### ISSUE THREAD

**Issue by klint-k** [Ekultek/WhatWaf#135]
python3 whatwaf.py --help
Traceback (most recent call last):
  File "whatwaf.py", line 7, in <module>
    main()
  File "/root/whatwaf/whatwaf/main.py", line 42, in main
    opt = WhatWafParser().cmd_parser()
  File "/root/whatwaf/lib/cmd.py", line 140, in cmd_parser
    opts = parser.parse_args()
  File "/usr/lib/python3.6/argparse.py", line 1743, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python3.6/argparse.py", line 1775, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.6/argparse.py", line 1981, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib/python3.6/argparse.py", line 1921, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib/python3.6/argparse.py", line 1849, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/lib/python3.6/argparse.py", line 1033, in __call__
    parser.print_help()
  File "/usr/lib/python3.6/argparse.py", line 2375, in print_help
    self._print_message(self.format_help(), file)
  File "/usr/lib/python3.6/argparse.py", line 2359, in format_help
    return formatter.format_help()
  File "/usr/lib/python3.6/argparse.py", line 291, in format_help
    help = self._root_section.format_help()
  File "/usr/lib/python3.6/argparse.py", line 222, in format_help
    item_help = join([func(*args) for func, args in self.items])
  File "/usr/lib/python3.6/argparse.py", line 222, in <listcomp>
    item_help = join([func(*args) for func, args in self.items])
  File "/usr/lib/python3.6/argparse.py", line 222, in format_help
    item_help = join([func(*args) for func, args in self.items])
  File "/usr/lib/python3.6/argparse.py", line 222, in <listcomp>
    item_help = join([func(*args) for func, args in self.items])
  File "/usr/lib/python3.6/argparse.py", line 532, in _format_action
    help_text = self._expand_help(action)
  File "/usr/lib/python3.6/argparse.py", line 619, in _expand_help
    return self._get_help_string(action) % params
TypeError: must be real number, not dict

**Comment by Ekultek** [comment]
What python version? Is help the only command that isn’t working? Try this:
```
python3 whatwaf.py -u “http://crackme.cenzic.com/kelev/view/home.php” —ra —traffic traffic.txt —verbose —skip
```

**Comment by klint-k** [comment]
python3 whatwaf.py --help
python3 whatwaf.py -u “http://crackme.cenzic.com/kelev/view/home.php” —ra —traffic traffic.txt —verbose —skip
usage: ./whatwaf.py -[u|l|b|g] VALUE|PATH|PATH|PATH [-p|--pl] PAYLOAD,..|PATH [--args]
whatwaf.py: error: unrecognized arguments: —ra —traffic traffic.txt —verbose —skip


Sorry for the delay. I hope that this helps
