### ISSUE TITLE
Namespace error

### ISSUE THREAD

**Issue by klint-k** [Ekultek/WhatWaf#138]
python3 whatwaf.py -u “http://crackme.cenzic.com/kelev/view/home.php”
Traceback (most recent call last):
  File "whatwaf.py", line 12, in <module>
    main()
  File "/root/whatwaf/whatwaf/main.py", line 42, in main
    opt = WhatWafParser().cmd_parser()
  File "/root/whatwaf/lib/cmd.py", line 141, in cmd_parser
    opts.log.write('%s' % sum(args.integers))
AttributeError: 'Namespace' object has no attribute 'log'

**Comment by Ekultek** [comment]
Fucking python3

**Comment by Ekultek** [comment]
Ping?

**Comment by Ekultek** [comment]
no response
