### ISSUE TITLE
create setup.py and support system-wide installation

### ISSUE THREAD

**Issue by blshkv** [Ekultek/WhatWaf#628]
The existing setup.sh is a wrong way of doing it.
Please create a proper setup.py, expect that will be installed as a python module (read-only) and redirect all output into a home  folder, something like ~/.WhatWaf/*

It can be still installed (properly) into a local folder using the following command:
``` python setup.py install --user```

**Comment by Ekultek** [comment]
done

**Comment by blshkv** [comment]
Thanks! Almost there. There is a problem with data files:
```
whatwaf 
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.6/whatwaf", line 3, in <module>
    from trigger.main import main
  File "/usr/lib64/python3.6/site-packages/trigger/main.py", line 6, in <module>
    from lib.cmd import WhatWafParser
  File "/usr/lib64/python3.6/site-packages/lib/cmd.py", line 7, in <module>
    import lib.settings
  File "/usr/lib64/python3.6/site-packages/lib/settings.py", line 131, in <module>
    WAF_REQUEST_DETECTION_PAYLOADS = [p.strip() for p in open(DEFAULT_PAYLOAD_PATH).readlines()]
FileNotFoundError: [Errno 2] No such file or directory: '<homedir>/content/files/default_payloads.lst'
```

I dont see it is getting installed

**Comment by blshkv** [comment]
https://github.com/derv82/wifite2/issues/102 if you need an example how to install it

**Comment by Ekultek** [comment]
It's working for me, that's weird kinda..

**Comment by Ekultek** [comment]
```
whatwaf -u https://google.com -c --ra --tor --check-tor -W -FJ

	                          ,------.
	                         '  .--.  '
	,--.   .--.   ,--.   .--.|  |  |  |
	|  |   |  |   |  |   |  |'--'  |  |
	|  |   |  |   |  |   |  |    __.  |
	|  |.'.|  |   |  |.'.|  |   |   .'
	|         |   |         |   |___|
	|   ,'.   |hat|   ,'.   |af .---.
	'--'   '--'   '--'   '--'   '---'
/&gt;&lt;script&gt;alert("WhatWaf?<|>v1.8.2($dev)");&lt;/script&gt;

[01:55:38][INFO] checking for updates
[01:55:38][WARN] there is an update available for whatwaf
[01:55:38][INFO] running behind proxy 'socks5://127.0.0.1:9050'
[01:55:38][INFO] using User-Agent 'Opera/8.50 (Windows NT 5.0; U; fr)'
[01:55:38][INFO] checking Tor connection
[01:55:40][SUCCESS] it appears that Tor is working properly
[01:55:40][INFO] using default payloads
[01:55:40][INFO] testing connection to target URL before starting attack (Tor is initialized which may increase latency)
[01:55:43][SUCCESS] connection succeeded, continuing
[01:55:43][INFO] running single web application 'https://google.com'
[01:55:43][WARN] URL does not appear to have a query (parameter), this may interfere with the detection results
[01:55:43][INFO] request type: GET
[01:55:43][INFO] gathering HTTP responses
```

**Comment by blshkv** [comment]
That's probably because you have these files in the home dir?

**Comment by Ekultek** [comment]
```
$ sudo pip3 uninstall whatwaf
The directory '/home/loki/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Uninstalling whatwaf-1.8.2:
  /usr/local/lib/python3.6/dist-packages/whatwaf-1.8.2-py3.6.egg
Proceed (y/n)? y
  Successfully uninstalled whatwaf-1.8.2
$ rm -rf ~/.whatwaf/
$ sudo python3 setup.py install
running install
running bdist_egg
running egg_info
writing whatwaf.egg-info/PKG-INFO
writing dependency_links to whatwaf.egg-info/dependency_links.txt
writing requirements to whatwaf.egg-info/requires.txt
writing top-level names to whatwaf.egg-info/top_level.txt
reading manifest file 'whatwaf.egg-info/SOURCES.txt'
writing manifest file 'whatwaf.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/content
copying build/lib/content/__init__.py -> build/bdist.linux-x86_64/egg/content
creating build/bdist.linux-x86_64/egg/content/plugins
copying build/lib/content/plugins/webseal.py -> build/bdist.linux-x86_64/egg/content/plugins
copying build/lib/content/plugins/stricthttp.py -> build/bdist.linux-x86_64/egg/content/plugins
copying build/lib/content/plugins/cloudflare.py -> build/bdist.linux-x86_64/egg/content/plugins
copying build/lib/content/plugins/nginxgeneric.py -> build/bdist.linux-x86_64/egg/content/plugins
copying build/lib/content/plugins/litespeed.py -> build/bdist.linux-x86_64/egg/content/plugins
copying build/lib/content/plugins/denyall.py -> build/bdist.linux-x86_64/egg/content/plugins
copying build/lib/content/plugins/anquanbao.py -> build/bdist.linux-x86_64/egg/content/plugins
copying build/lib/content/plugins/instart.py -> build/bdist.linux-x86_64/egg/content/plugins
copying build/lib/content/plugins/bitninja.py -> build/bdist.linux-x86_64/egg/content/plugins
copying build/lib/content/plugins/aws.py -> build/bdist.linux-x86_64/egg/content/plugins
copying build/lib/content/plugins/googlewebservices.py -> build/bdist.linux-x86_64/egg/content/plugins
copying build/lib/content/plugins/__init__.py -> build/bdist.linux-x86_64/egg/content/plugins
copying build/lib/content/plugins/chuangyu.py -> build/bdist.linux-x86_64/egg/content/plugins
copying build/lib/content/plugins/powerful.py -> build/bdist.linux-x86_64/egg/content/plugins
copying build/lib/content/plugins/yunsuo.py -> build/bdist.linux-x86_64/egg/content/plugins
copying build/lib/content/plugins/didiyun.py -> build/bdist.linux-x86_64/egg/content/plugins
copying build/lib/content/plugins/bekchy.py -> build/bdist.linux-x86_64/egg/content/plugins
copying build/lib/content/plugins/paloalto.py -> build/bdist.linux-x86_64/egg/content/plugins
copying build/lib/content/plugins/fortigate.py -> build/bdist.linux-x86_64/egg/content/plugins
copying build/lib/content/plugins/wallarm.py -> build/bdist.linux-x86_64/egg/content/plugins
copying build/lib/content/plugins/edgecast.py -> build/bdist.linux-x86_64/egg/content/plugins
copying build/lib/content/plugins/pk.py -> build/bdist.linux-x86_64/egg/content/plugins
copying build/lib/content/plugins/webknight.py -> build/bdist.linux-x86_64/egg/content/plugins
copying build/lib/content/plugins/airlock.py -> build/bdist.linux-x86_64/egg/content/plugins
copying build/lib/content/plugins/janusec.py -> build/bdist.linux-x86_64/egg/content/plugins
copying build/lib/content/plugins/sucuri.py -> build/bdist.linux-x86_64/egg/content/plugins
copying build/lib/content/plugins/nexusguard.py -> build/bdist.linux-x86_64/egg/content/plugins
copying build/lib/content/plugins/apachegeneric.py -> build/bdist.linux-x86_64/egg/content/plugins
copying build/lib/content/plugins/modsecurityowasp.py -> build/bdist.linux-x86_64/egg/content/plugins
copying build/lib/content/plugins/jiasule.py -> build/bdist.linux-x86_64/egg/content/plugins
copying build/lib/content/plugins/stingray.py -> build/bdist.linux-x86_64/egg/content/plugins
copying build/lib/content/plugins/west263.py -> build/bdist.linux-x86_64/egg/content/plugins
copying build/lib/content/plugins/360.py -> build/bdist.linux-x86_64/egg/content/plugins
copying build/lib/content/plugins/viettel.py -> build/bdist.linux-x86_64/egg/content/plugins
copying build/lib/content/plugins/expressionengine.py -> build/bdist.linux-x86_64/egg/content/plugins
copying build/lib/content/plugins/xuanwudun.py -> build/bdist.linux-x86_64/egg/content/plugins
copying build/lib/content/plugins/baidu.py -> build/bdist.linux-x86_64/egg/content/plugins
copying build/lib/content/plugins/codeigniter.py -> build/bdist.linux-x86_64/egg/content/plugins
copying build/lib/content/plugins/yundun.py -> build/bdist.linux-x86_64/egg/content/plugins
copying build/lib/content/plugins/ciscoacexml.py -> build/bdist.linux-x86_64/egg/content/plugins
copying build/lib/content/plugins/bigip.py -> build/bdist.linux-x86_64/egg/content/plugins
copying build/lib/content/plugins/dodenterpriseprotection.py -> build/bdist.linux-x86_64/egg/content/plugins
copying build/lib/content/plugins/siteguard.py -> build/bdist.linux-x86_64/egg/content/plugins
copying build/lib/content/plugins/modsecurity.py -> build/bdist.linux-x86_64/egg/content/plugins
copying build/lib/content/plugins/perimx.py -> build/bdist.linux-x86_64/egg/content/plugins
copying build/lib/content/plugins/shadowd.py -> build/bdist.linux-x86_64/egg/content/plugins
copying build/lib/content/plugins/armor.py -> build/bdist.linux-x86_64/egg/content/plugins
copying build/lib/content/plugins/rsfirewall.py -> build/bdist.linux-x86_64/egg/content/plugins
copying build/lib/content/plugins/secupress.py -> build/bdist.linux-x86_64/egg/content/plugins
copying build/lib/content/plugins/asm.py -> build/bdist.linux-x86_64/egg/content/plugins
copying build/lib/content/plugins/greywizard.py -> build/bdist.linux-x86_64/egg/content/plugins
copying build/lib/content/plugins/gladius.py -> build/bdist.linux-x86_64/egg/content/plugins
copying build/lib/content/plugins/incapsula.py -> build/bdist.linux-x86_64/egg/content/plugins
copying build/lib/content/plugins/shieldsecurity.py -> build/bdist.linux-x86_64/egg/content/plugins
copying build/lib/content/plugins/barracuda.py -> build/bdist.linux-x86_64/egg/content/plugins
...
zip_safe flag not set; analyzing archive contents...
creating 'dist/whatwaf-1.8.2-py3.6.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing whatwaf-1.8.2-py3.6.egg
Copying whatwaf-1.8.2-py3.6.egg to /usr/local/lib/python3.6/dist-packages
Adding whatwaf 1.8.2 to easy-install.pth file
Installing whatwaf script to /usr/local/bin

Installed /usr/local/lib/python3.6/dist-packages/whatwaf-1.8.2-py3.6.egg
Processing dependencies for whatwaf==1.8.2
Searching for requests==2.21.0
Best match: requests 2.21.0
Adding requests 2.21.0 to easy-install.pth file

Using /home/loki/.local/lib/python3.6/site-packages
Searching for beautifulsoup4==4.8.1
Best match: beautifulsoup4 4.8.1
Adding beautifulsoup4 4.8.1 to easy-install.pth file

Using /usr/local/lib/python3.6/dist-packages
Searching for idna==2.8
Best match: idna 2.8
Adding idna 2.8 to easy-install.pth file

Using /home/loki/.local/lib/python3.6/site-packages
Searching for urllib3==1.24.1
Best match: urllib3 1.24.1
Adding urllib3 1.24.1 to easy-install.pth file

Using /home/loki/.local/lib/python3.6/site-packages
Searching for chardet==3.0.4
Best match: chardet 3.0.4
Adding chardet 3.0.4 to easy-install.pth file
Installing chardetect script to /usr/local/bin

Using /usr/lib/python3/dist-packages
Searching for certifi==2018.11.29
Best match: certifi 2018.11.29
Adding certifi 2018.11.29 to easy-install.pth file

Using /home/loki/.local/lib/python3.6/site-packages
Searching for soupsieve==1.9.5
Best match: soupsieve 1.9.5
Adding soupsieve 1.9.5 to easy-install.pth file

Using /usr/local/lib/python3.6/dist-packages
Finished processing dependencies for whatwaf==1.8.2
$ whatwaf -u https://google.com -W --ra --tor --check-tor -c 

	                          ,------.
	                         '  .--.  '
	,--.   .--.   ,--.   .--.|  |  |  |
	|  |   |  |   |  |   |  |'--'  |  |
	|  |   |  |   |  |   |  |    __.  |
	|  |.'.|  |   |  |.'.|  |   |   .'
	|         |   |         |   |___|
	|   ,'.   |hat|   ,'.   |af .---.
	'--'   '--'   '--'   '--'   '---'
/><s/**/cript>alert("WhatWaf?<|>v1.8.2($dev)");</script>

[01:59:38][INFO] checking for updates
[01:59:38][WARN] there is an update available for whatwaf
[01:59:38][INFO] running behind proxy 'socks5://127.0.0.1:9050'
[01:59:38][INFO] using User-Agent 'Mozilla/5.0 (X11; U; Linux x86_64; en-US; rv:1.9.2a1pre) Gecko/20090428 Firefox/3.6a1pre'
[01:59:38][INFO] checking Tor connection
```

Still works after deleting the home dir

**Comment by blshkv** [comment]
Perhaps, I need to explain. I just installed ```python setup.py install``` and didn't run setup.sh after that.
Here is the list of what I got after installation:
http://dpaste.com/3ATGHQ2

the affected ```content/files/default_payloads.lst``` file is not in the list

**Comment by Ekultek** [comment]
No I understand what you're saying, I have an idea give me a second

**Comment by Ekultek** [comment]
pull from branch `beta` and try that, if that doesn't work i have another idea that might

**Comment by Ekultek** [comment]
Yo this should be fixed via https://github.com/Ekultek/WhatWaf/commit/467d8fb228598e0dda9f40aa48fe258bc445da53. There is however a couple problems, the way I designed the program in the first place makes it a little more complicated to do so I had to create an `install_helper` script that will move everything into the `HOME` directory as well. Also if it's run as root it's going to prompt for a username that way we can fix any permission issues that may occur. 

So the reasons this wasn't working:
 - plugins and tampers directory is "assumed" to be in the current directory, I fixed this by adding an except clause that will change the constant to the home directory. That way if people decide they don't want to install it onto their system, they can still run it from the current directory
 - the rest of the "data" files also did the same thing and assumed the user was within the current directory, fixed this by just copying all the data over with rsync (if you don't have rsync it will probably be a problem, but most distros come with it preinstalled). So basically `install_helper` just copies all the files and creates a database file to avoid more issues. 

I've tested this thoroughly if you find any issues with it please let me know.

**Comment by blshkv** [comment]
can you please move "rsync" portion during run time of whatwaf binary?
The common way is to install the core as root and create ~/.whatwaf for each user who runs it.

Also, I'm not able to install it right now due to this interaction. I'm getting the following message:
```
>>> Install net-analyzer/WhatWaf-1.8_p20191101 into /var/tmp/portage/net-analyzer/WhatWaf-1.8_p20191101/image/
 * python2_7: running distutils-r1_run_phase distutils-r1_python_install
python2.7 setup.py install --root=/var/tmp/portage/net-analyzer/WhatWaf-1.8_p20191101/image/_python2.7
what is your username (needed for directory fixes): [08:13:07][FATAL] WhatWaf has caught an unhandled exception with the error message: 'EOF when reading a line'.
[08:13:07][ERROR] 
------------------------------
Traceback (most recent call):
  File "setup.py", line 21, in <module>
    username = raw_input("what is your username (needed for directory fixes): ")
EOF when reading a line
------------------------------
[08:13:07][PROMPT] would you like to create an anonymized issue for the unhandled exception[y/N]: Traceback (most recent call last):
  File "setup.py", line 55, in <module>
    request_issue_creation(exception_data)
  File "/var/tmp/portage/net-analyzer/WhatWaf-1.8_p20191101/work/WhatWaf-467d8fb228598e0dda9f40aa48fe258bc445da53/lib/firewall_found.py", line 108, in request_issue_creation
    "would you like to create an anonymized issue for the unhandled exception", "yN"
  File "/var/tmp/portage/net-analyzer/WhatWaf-1.8_p20191101/work/WhatWaf-467d8fb228598e0dda9f40aa48fe258bc445da53/lib/formatter.py", line 79, in prompt
    time.strftime("%H:%M:%S"), string, "/".join(opts)
EOFError: EOF when reading a line
 * ERROR: net-analyzer/WhatWaf-1.8_p20191101::pentoo failed (install phase):
 *   (no error message)
```

**Comment by blshkv** [comment]
FYI, there is a python wrapper of rsync:
https://pypi.org/project/sysrsync/ (just a first search result from google)
 or
https://github.com/pimutils/vdirsyncer

You can get rid of bash script and call it properly from whatwaf

**Comment by blshkv** [comment]
ping? It would be good to complete the last bit before I forgot all details.

**Comment by Ekultek** [comment]
@blshkv hey sorry, been busy. I'll get it done in the next couple of days and let you know

**Comment by Ekultek** [comment]
hi sorry for the delay, there is no reason to add another dependency to it that only accomplishes a single thing. I think the install_helper.sh script is good enough for the purpose

**Comment by blshkv** [comment]
sorry, but think you missed the point. I'm unable to install interactive setup.py:

```
>>> Install net-analyzer/WhatWaf-1.9_p20191216 into /var/tmp/portage/net-analyzer/WhatWaf-1.9_p20191216/image/
 * python2_7: running distutils-r1_run_phase distutils-r1_python_install
python2.7 setup.py install --root=/var/tmp/portage/net-analyzer/WhatWaf-1.9_p20191216/image/_python2.7
what is your username (needed for directory fixes): [10:30:17][FATAL] WhatWaf has caught an unhandled exception with the error message: 'EOF when reading a line'.
[10:30:17][ERROR] 
------------------------------
Traceback (most recent call):
  File "setup.py", line 21, in <module>
    username = raw_input("what is your username (needed for directory fixes): ")
EOF when reading a line
------------------------------
[10:30:17][PROMPT] would you like to create an anonymized issue for the unhandled exception[y/N]: Traceback (most recent call last):
  File "setup.py", line 59, in <module>
    request_issue_creation(exception_data)
  File "/var/tmp/portage/net-analyzer/WhatWaf-1.9_p20191216/work/WhatWaf-625d6247f3f4f361339761bc231cd599c6b60767/lib/firewall_found.py", line 108, in request_issue_creation
    "would you like to create an anonymized issue for the unhandled exception", "yN"
  File "/var/tmp/portage/net-analyzer/WhatWaf-1.9_p20191216/work/WhatWaf-625d6247f3f4f361339761bc231cd599c6b60767/lib/formatter.py", line 79, in prompt
    time.strftime("%H:%M:%S"), string, "/".join(opts)
EOFError: EOF when reading a line
 * ERROR: net-analyzer/WhatWaf-1.9_p20191216::pentoo failed (install phase):
```

**Comment by blshkv** [comment]
Ping? Please re-open the issue as I can't
