### ISSUE TITLE
[FATAL] WhatWaf has caught an unhandled exception with the error message: 'Invalid percent-escape sequence: 'u0''

### ISSUE THREAD

**Issue by hinokop** [Ekultek/WhatWaf#76]
Traceback:
```
Traceback (most recent call last):
  File "/root/WhatWaf/whatwaf/main.py", line 194, in main
    fingerprint_waf=opt.saveFingerprints, provided_headers=opt.extraHeaders
  File "/root/WhatWaf/content/__init__.py", line 395, in detection_main
    tamper_int=tamper_int
  File "/root/WhatWaf/content/__init__.py", line 163, in get_working_tampers
    payloaded_url, agent=agent, proxy=proxy, verbose=verbose, provided_headers=provided_headers
  File "/root/WhatWaf/lib/settings.py", line 176, in get_page
    req = requests.get(url, headers=headers, proxies=proxies, timeout=15)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.5.0-py2.7.egg/requests/api.py", line 65, in get
    return request('get', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.5.0-py2.7.egg/requests/api.py", line 49, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.5.0-py2.7.egg/requests/sessions.py", line 447, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.5.0-py2.7.egg/requests/sessions.py", line 378, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/local/lib/python2.7/dist-packages/requests-2.5.0-py2.7.egg/requests/models.py", line 304, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.5.0-py2.7.egg/requests/models.py", line 400, in prepare_url
    url = requote_uri(urlunparse([scheme, netloc, path, None, query, fragment]))
  File "/usr/local/lib/python2.7/dist-packages/requests-2.5.0-py2.7.egg/requests/utils.py", line 424, in requote_uri
    return quote(unquote_unreserved(uri), safe="!#$%&'()*+,/:;=?@[]~")
  File "/usr/local/lib/python2.7/dist-packages/requests-2.5.0-py2.7.egg/requests/utils.py", line 404, in unquote_unreserved
    raise InvalidURL("Invalid percent-escape sequence: '%s'" % h)
InvalidURL: Invalid percent-escape sequence: 'u0'
```
CMD line: `whatwaf.py -u *********************`

**Comment by Ekultek** [comment]
thank you

**Comment by hinokop** [comment]
getting this error when trying to ./install.sh : Traceback (most recent call last):
  File "/usr/local/bin/pip", line 7, in <module>
    from pip._internal import main
  File "/usr/lib/python3/dist-packages/pip/__init__.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python3/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python3/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name 'IncompleteRead'

**Comment by hinokop** [comment]
and this one when trying to pip install requirements.txt : Traceback (most recent call last):
  File "/usr/local/bin/pip", line 7, in <module>
    from pip._internal import main
  File "/usr/lib/python3/dist-packages/pip/__init__.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python3/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python3/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name 'IncompleteRead'

**Comment by Ekultek** [comment]
For the first one, your URL is invalid (still has url entities in it) I have a possible fix for that. The other two are your pip installation, run the following to fix those:

```
sudo apt-get remove python-pip --purge
sudo apt-get install python-pip
```

**Comment by Ekultek** [comment]
patched via https://github.com/Ekultek/WhatWaf/commit/a14027d0a018d8f7081e77263e572f29fc8bec26
